services:
  bitchord-selfhosted-addon:
    image: ghcr.io/rairulyle/bitchord-selfhosted-addon:latest
    restart: unless-stopped
    volumes:
      - data:/data
    networks:
      - proxy

volumes:
  data:

networks:
  proxy:
    external: true
    name: replace-with-your-reverse-proxy-network
