services:
  eclipse-plex-addon:
    image: ghcr.io/rairulyle/eclipse-plex-addon:latest
    restart: unless-stopped
    env_file: .env
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: replace-with-your-reverse-proxy-network
