services:
  bitchord-selfhosted-addon:
    image: ghcr.io/rairulyle/bitchord-selfhosted-addon:latest
    ports:
      - "8080:8080"
    volumes:
      - </path/to/your/data>:/data
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: replace-with-your-reverse-proxy-network
